### ISSUE TITLE
Netbox 3.3 support

### ISSUE THREAD

**Issue by jhjadmin** [iDebugAll/phonebox_plugin#27]
Hi,

while installing I run in the same error as [Issue #10080](https://github.com/netbox-community/netbox/discussions/10080). Is there any kind of roadmap/planned support for 3.3?

**Comment by dywilson73** [comment]
I was looking at this too - but need support for 3.3 - Would love to know if an update is planned.

**Comment by DavidWoffendin** [comment]
Any update for 3.3 would be appreciated

**Comment by jhjadmin** [comment]
> Hello, Easy to solve this issue : you just need to edit nested_serializers.py located in phonebox_plugin/api folder === replace === from netbox.api import WritableNestedSerializer === by === # for netbox 3.3 try: from netbox.api import WritableNestedSerializer except ImportError: from netbox.api.serializers.nested import WritableNestedSerializer
> 
> after that : (venv) $ python3 manage.py migrate sudo systemctl restart netbox all's working fine

Hi and thanks for your answer but unfortunately this doesn't work for me or I misunderstand you. With your changes my nested_serializers.py looks like this:

```
from rest_framework import serializers
from phonebox_plugin import models
# for netbox 3.3
try:
    from netbox.api import WritableNestedSerializer
except ImportError:
    from netbox.api.serializers.nested import WritableNestedSerializer
from tenancy.api.nested_serializers import NestedTenantSerializer

__all__ = ["NestedNumberSerializer", ]


class NestedNumberSerializer(WritableNestedSerializer):

    label = serializers.CharField(source='number', read_only=True)
    tenant = NestedTenantSerializer(required=True, allow_null=False)

    class Meta:
        model = models.Number
        fields = [
            "id", "label", "number", "tenant",
        ]
```

When running the manage.py script it throws errors:
`
ImportError: cannot import name 'WritableNestedSerializer' from 'netbox.api' (/srv/netbox/netbox/netbox/api/__init__.py)
`

What am I missing?

Thanks in regard for your help.

**Comment by dywilson73** [comment]
weird 
The email notification i got for this issue said the following 

> Easy to solve this issue :
> you just need to edit nested_serializers.py located in phonebox_plugin/api folder
> === replace ===
> from netbox.api import WritableNestedSerializer
> === by ===
> 
> for netbox 3.3
> 
> try:
> from netbox.api import ChoiceField, WritableNestedSerializer
> except ImportError:
> from netbox.api.fields import ChoiceField
> from netbox.api.serializers.nested import WritableNestedSerializer
> 
> after that :
> (venv) $ python3 manage.py migrate
> sudo systemctl restart netbox
> all's working fine

so the imports section of mine lookes like this - and it works. 



```
from phonebox_plugin import models
try:
    from netbox.api import ChoiceField, WritableNestedSerializer
except ImportError:
    from netbox.api.fields import ChoiceField
    from netbox.api.serializers.nested import WritableNestedSerializer
from tenancy.api.nested_serializers import NestedTenantSerializer
```

**Comment by jhjadmin** [comment]
Still no luck with your changes. I pasted it 1:1 and got the same error. Could it have something to do with the underlying OS? I am running netbox on an Ubuntu 20.04 server.

**Comment by DavidWoffendin** [comment]
Same still getting the same error

Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 98, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 91, in handle
    self.check(databases=[database])
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 480, in check
    for pattern in self.url_patterns:
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/urls.py", line 9, in <module>
    from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
  File "/opt/netbox/netbox/extras/plugins/urls.py", line 35, in <module>
    urlpatterns = import_object(f"{plugin_path}.api.urls.urlpatterns")
  File "/opt/netbox/netbox/extras/plugins/utils.py", line 31, in import_object
    spec.loader.exec_module(module)
  File "/opt/netbox/venv/lib/python3.10/site-packages/phonebox_plugin/api/urls.py", line 2, in <module>
    from . import views
  File "/opt/netbox/venv/lib/python3.10/site-packages/phonebox_plugin/api/views.py", line 4, in <module>
    from . import serializers
  File "/opt/netbox/venv/lib/python3.10/site-packages/phonebox_plugin/api/serializers.py", line 8, in <module>
    from .nested_serializers import NestedNumberSerializer
  File "/opt/netbox/venv/lib/python3.10/site-packages/phonebox_plugin/api/nested_serializers.py", line 3, in <module>
    from netbox.api import WritableNestedSerializer
ImportError: cannot import name 'WritableNestedSerializer' from 'netbox.api' (/opt/netbox/netbox/netbox/api/__init__.py)

**Comment by anton-spec** [comment]
CentOS Linux release 7.9.2009 (Core)

(venv) [root@web netbox]# python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/core/management/base.py", line 98, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 91, in handle
    self.check(databases=[database])
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 480, in check
    for pattern in self.url_patterns:
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox-3.3.8/netbox/netbox/urls.py", line 9, in <module>
    from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
  File "/opt/netbox-3.3.8/netbox/extras/plugins/urls.py", line 35, in <module>
    urlpatterns = import_object(f"{plugin_path}.api.urls.urlpatterns")
  File "/opt/netbox-3.3.8/netbox/extras/plugins/utils.py", line 31, in import_object
    spec.loader.exec_module(module)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/phonebox_plugin/api/urls.py", line 2, in <module>
    from . import views
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/phonebox_plugin/api/views.py", line 4, in <module>
    from . import serializers
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/phonebox_plugin/api/serializers.py", line 8, in <module>
    from .nested_serializers import NestedNumberSerializer
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/phonebox_plugin/api/nested_serializers.py", line 4
    from netbox.api import ChoiceField, WritableNestedSerializer
    ^

**Comment by anton-spec** [comment]
OR
CentOS Linux release 7.9.2009 (Core)

`(venv) [root@web api]# cat nested_serializers.py
from rest_framework import serializers
from phonebox_plugin import models
try:
from netbox.api import WritableNestedSerializer
except ImportError:
from netbox.api.serializers.nested import WritableNestedSerializer
from tenancy.api.nested_serializers import NestedTenantSerializer

__all__ = ["NestedNumberSerializer", ]
-cut-`

(venv) [root@web netbox]# python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/core/management/base.py", line 98, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 91, in handle
    self.check(databases=[database])
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/core/management/base.py", line 487, in check
    all_issues = checks.run_checks(
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 480, in check
    for pattern in self.url_patterns:
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox-3.3.8/netbox/netbox/urls.py", line 9, in <module>
    from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
  File "/opt/netbox-3.3.8/netbox/extras/plugins/urls.py", line 35, in <module>
    urlpatterns = import_object(f"{plugin_path}.api.urls.urlpatterns")
  File "/opt/netbox-3.3.8/netbox/extras/plugins/utils.py", line 31, in import_object
    spec.loader.exec_module(module)
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/phonebox_plugin/api/urls.py", line 2, in <module>
    from . import views
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/phonebox_plugin/api/views.py", line 4, in <module>
    from . import serializers
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/phonebox_plugin/api/serializers.py", line 8, in <module>
    from .nested_serializers import NestedNumberSerializer
  File "/opt/netbox-3.3.8/venv/lib/python3.8/site-packages/phonebox_plugin/api/nested_serializers.py", line 5
    from netbox.api import WritableNestedSerializer
    ^
IndentationError: expected an indented block

**Comment by jhjadmin** [comment]
Please use the correct format. Your error states `IndentationError: expected an indented block` and has nothing to do with my error. For python it is essential that you use correct indentation, so your error results from a mistake in your editing.

**Comment by InsaneSplash** [comment]
I tried to re-install this with Netbox 3.4.0 which worked fine, except that when trying to click on the plugin link, I have the below error returned.
![image](https://user-images.githubusercontent.com/16985649/208174185-536b2a5f-e889-4187-b8e4-0ef8d55d6e42.png)

**Comment by anton-spec** [comment]
> Please use the correct format. Your error states `IndentationError: expected an indented block` and has nothing to do with my error. For python it is essential that you use correct indentation, so your error results from a mistake in your editing.

thx, 
all works.

(venv) [root@web netbox]# python3 manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, django_rq, extras, ipam, phonebox_plugin, sessions, social_django, taggit, tenancy, users, virtualization, wireless
Running migrations:
  Applying phonebox_plugin.0001_initial... OK
  Applying phonebox_plugin.0002_alter_number_id... OK
  Applying phonebox_plugin.0003_voicecircuit... OK

**Comment by hblandford** [comment]
> I tried to re-install this with Netbox 3.4.0 which worked fine, except that when trying to click on the plugin link, I have the below error returned. ![image](https://user-images.githubusercontent.com/16985649/208174185-536b2a5f-e889-4187-b8e4-0ef8d55d6e42.png)

I am running v3.4.1 and fixed this problem by updating the templates:

cd phonebox_plugin/phonebox_plugin/templates/phonebox_plugin/
list_view_3.x.html (line 62):               {% applied_filters filter_form request.GET %}
voice_circuit_list_view_3.x.html (line 62):                 {% applied_filters filter_form request.GET %}

to 

list_view_3.x.html (line 62):               {% applied_filters model filter_form request.GET %}
voice_circuit_list_view_3.x.html (line 62):                 {% applied_filters model filter_form request.GET %}

Hope that helps.

**Comment by jhjadmin** [comment]
After updating to 3.4 the plugin is listed but I am getting as well an internal server error 500. The changes

> > I tried to re-install this with Netbox 3.4.0 which worked fine, except that when trying to click on the plugin link, I have the below error returned. ![image](https://user-images.githubusercontent.com/16985649/208174185-536b2a5f-e889-4187-b8e4-0ef8d55d6e42.png)
> 
> I am running v3.4.1 and fixed this problem by updating the templates:
> 
> cd phonebox_plugin/phonebox_plugin/templates/phonebox_plugin/ list_view_3.x.html (line 62): {% applied_filters filter_form request.GET %} voice_circuit_list_view_3.x.html (line 62): {% applied_filters filter_form request.GET %}
> 
> to
> 
> list_view_3.x.html (line 62): {% applied_filters model filter_form request.GET %} voice_circuit_list_view_3.x.html (line 62): {% applied_filters model filter_form request.GET %}
> 
> Hope that helps.

After updating to 3.4 the plugin is listed but I am getting as well an internal server error 500. When I run ```python3 manage.py migrate``` it throws the error:

```
  Your models in app(s): 'phonebox_plugin' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

If I run the ```python3 manage.py makemigrations``` it throws another error
```
CommandError: This command is available for development purposes only. It will
NOT resolve any issues with missing or unapplied migrations. For assistance,
please post to the NetBox discussion forum on GitHub:
    https://github.com/netbox-community/netbox/discussions
```

What I am wondering is, that the changes in ```list_view_3.x.html``` and ```voice_circuit_list_view_3.x.html``` is on line 47 and not 62. The files only have 62 lines in total. Do I have other templates than you? Mine are equal to the ones on github.

**Comment by trakennedy** [comment]
> After updating to 3.4 the plugin is listed but I am getting as well an internal server error 500. The changes
> 
> > > I tried to re-install this with Netbox 3.4.0 which worked fine, except that when trying to click on the plugin link, I have the below error returned. ![image](https://user-images.githubusercontent.com/16985649/208174185-536b2a5f-e889-4187-b8e4-0ef8d55d6e42.png)
> > 
> > 
> > I am running v3.4.1 and fixed this problem by updating the templates:
> > cd phonebox_plugin/phonebox_plugin/templates/phonebox_plugin/ list_view_3.x.html (line 62): {% applied_filters filter_form request.GET %} voice_circuit_list_view_3.x.html (line 62): {% applied_filters filter_form request.GET %}
> > to
> > list_view_3.x.html (line 62): {% applied_filters model filter_form request.GET %} voice_circuit_list_view_3.x.html (line 62): {% applied_filters model filter_form request.GET %}
> > Hope that helps.
> 
> After updating to 3.4 the plugin is listed but I am getting as well an internal server error 500. When I run `python3 manage.py migrate` it throws the error:
> 
> ```
>   Your models in app(s): 'phonebox_plugin' have changes that are not yet reflected in a migration, and so won't be applied.
>   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
> ```
> 
> If I run the `python3 manage.py makemigrations` it throws another error
> 
> ```
> CommandError: This command is available for development purposes only. It will
> NOT resolve any issues with missing or unapplied migrations. For assistance,
> please post to the NetBox discussion forum on GitHub:
>     https://github.com/netbox-community/netbox/discussions
> ```
> 
> What I am wondering is, that the changes in `list_view_3.x.html` and `voice_circuit_list_view_3.x.html` is on line 47 and not 62. The files only have 62 lines in total. Do I have other templates than you? Mine are equal to the ones on github.

I have the same issue, exact same line numbers. I'm deactivating the plugin for now but anxiously awaiting a fix by someone with more than my 30 seconds of Python experience.

**Comment by PVM-NL** [comment]
> > I tried to re-install this with Netbox 3.4.0 which worked fine, except that when trying to click on the plugin link, I have the below error returned. ![image](https://user-images.githubusercontent.com/16985649/208174185-536b2a5f-e889-4187-b8e4-0ef8d55d6e42.png)
> 
> I am running v3.4.1 and fixed this problem by updating the templates:
> 
> cd phonebox_plugin/phonebox_plugin/templates/phonebox_plugin/ list_view_3.x.html (line 62): {% applied_filters filter_form request.GET %} voice_circuit_list_view_3.x.html (line 62): {% applied_filters filter_form request.GET %}
> 
> to
> 
> list_view_3.x.html (line 62): {% applied_filters model filter_form request.GET %} voice_circuit_list_view_3.x.html (line 62): {% applied_filters model filter_form request.GET %}
> 
> Hope that helps.

Can you provide a pull request to the main source. 
Might be that the creator will update the plugin.

@iDebugAll can you provide an update for 3.4?

**Comment by MikePetrov** [comment]
> > I tried to re-install this with Netbox 3.4.0 which worked fine, except that when trying to click on the plugin link, I have the below error returned. ![image](https://user-images.githubusercontent.com/16985649/208174185-536b2a5f-e889-4187-b8e4-0ef8d55d6e42.png)
> 
> I am running v3.4.1 and fixed this problem by updating the templates:
> 
> cd phonebox_plugin/phonebox_plugin/templates/phonebox_plugin/ list_view_3.x.html (line 62): {% applied_filters filter_form request.GET %} voice_circuit_list_view_3.x.html (line 62): {% applied_filters filter_form request.GET %}
> 
> to
> 
> list_view_3.x.html (line 62): {% applied_filters model filter_form request.GET %} voice_circuit_list_view_3.x.html (line 62): {% applied_filters model filter_form request.GET %}
> 
> Hope that helps.

A short and beautiful solution.
With a small addition: If the plugin was installed earlier, then it is located : 
%installation path%/netbox/venv/lib/python3/9/site-packages/phonebox-plugin/...
and the line number is 47 are not 62

**Comment by jhjadmin** [comment]
> > > I tried to re-install this with Netbox 3.4.0 which worked fine, except that when trying to click on the plugin link, I have the below error returned. ![image](https://user-images.githubusercontent.com/16985649/208174185-536b2a5f-e889-4187-b8e4-0ef8d55d6e42.png)
> > 
> > 
> > I am running v3.4.1 and fixed this problem by updating the templates:
> > cd phonebox_plugin/phonebox_plugin/templates/phonebox_plugin/ list_view_3.x.html (line 62): {% applied_filters filter_form request.GET %} voice_circuit_list_view_3.x.html (line 62): {% applied_filters filter_form request.GET %}
> > to
> > list_view_3.x.html (line 62): {% applied_filters model filter_form request.GET %} voice_circuit_list_view_3.x.html (line 62): {% applied_filters model filter_form request.GET %}
> > Hope that helps.
> 
> A short and beautiful solution. With a small addition: If the plugin was installed earlier, then it is located : %installation path%/netbox/venv/lib/python3/9/site-packages/phonebox-plugin/... and the line number is 47 are not 62

The "small edition" part did it for me now. After changing the two files as well under the mentioned path, it seems to work now.
