### ISSUE TITLE
SyntaxError: unmatched ']' in netbox-docker deployment

### ISSUE THREAD

**Issue by mstapi** [iDebugAll/phonebox_plugin#34]
Hello All,

After going through the installation steps listed in "Installation with Docker" I am getting the following error:

netbox-docker-netbox-1               | Traceback (most recent call last):
netbox-docker-netbox-1               |   File "/opt/netbox/netbox/./manage.py", line 10, in <module>
netbox-docker-netbox-1               |     execute_from_command_line(sys.argv)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
netbox-docker-netbox-1               |     utility.execute()
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 386, in execute
netbox-docker-netbox-1               |     settings.INSTALLED_APPS
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 87, in __getattr__
netbox-docker-netbox-1               |     self._setup(name)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 74, in _setup
netbox-docker-netbox-1               |     self._wrapped = Settings(settings_module)
netbox-docker-netbox-1               |   File "/opt/netbox/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 183, in __init__
netbox-docker-netbox-1               |     mod = importlib.import_module(self.SETTINGS_MODULE)
netbox-docker-netbox-1               |   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
netbox-docker-netbox-1               |     return _bootstrap._gcd_import(name[level:], package, level)
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
netbox-docker-netbox-1               |   File "/opt/netbox/netbox/netbox/settings.py", line 55, in <module>
netbox-docker-netbox-1               |     configuration = importlib.import_module(config_path)
netbox-docker-netbox-1               |   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
netbox-docker-netbox-1               |     return _bootstrap._gcd_import(name[level:], package, level)
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
netbox-docker-netbox-1               |   File "/opt/netbox/netbox/netbox/configuration.py", line 71, in <module>
netbox-docker-netbox-1               |     _loaded_configurations = read_configurations(
netbox-docker-netbox-1               |   File "/opt/netbox/netbox/netbox/configuration.py", line 33, in read_configurations
netbox-docker-netbox-1               |     _import(f"{config_module}.{main_config}", main_config_path, loaded_configurations)
netbox-docker-netbox-1               |   File "/opt/netbox/netbox/netbox/configuration.py", line 20, in _import
netbox-docker-netbox-1               |     spec.loader.exec_module(module)
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap_external>", line 851, in exec_module
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap_external>", line 988, in get_code
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap_external>", line 918, in source_to_code
netbox-docker-netbox-1               |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
netbox-docker-netbox-1               |   File "/etc/netbox/config/configuration.py", line 245
netbox-docker-netbox-1               |     ]
netbox-docker-netbox-1               |     ^
netbox-docker-netbox-1               | SyntaxError: unmatched ']'
netbox-docker-netbox-1               | ⏳ Waiting on DB... (27s / 30s)
netbox-docker-netbox-1               | ❌ Waited 30s or more for the DB to become ready.
netbox-docker-netbox-1 exited with code 1
dependency failed to start: container netbox-docker-netbox-1 exited (1)
admin@netboxlab:/apps/netbox-docker$ docker images
REPOSITORY               TAG          IMAGE ID       CREATED        SIZE
netbox-custom            latest       3539091e31b1   22 hours ago   483MB
netboxcommunity/netbox   v3.5-2.6.1   881e89b98c6b   7 days ago     577MB
redis                    7-alpine     0b405767398c   6 weeks ago    29.9MB
postgres                 15-alpine    ddc12ac7fa27   2 months ago   243MB
caddy                    2-alpine     86ab4e60cac2   2 months ago   46MB
netboxcommunity/netbox   v3.4-2.4.0   ae7cc0e4c678   2 months ago   632MB

Note: PLUGINS_CONFIG parameter is empty since I was unable to find any reference to settings that should potentially be added there.

Any idea why I may be getting this issue? I have tried originally with NetBox 3.4 and since updated to 3.5 but still hitting the same issue. Thank you very much in advance.

**Comment by N0mpumelel0** [comment]
Hi all 

Is anybody able to help with this issue. I am also interested in finding a solution to complete the installation of this plug-in.
