### ISSUE TITLE
NetBox 3.0.x

### ISSUE THREAD

**Issue by InsaneSplash** [iDebugAll/phonebox_plugin#8]
Hello,

Is it possible to update this plugin to support Netbox 3.0.x?

```
<class 'django.template.exceptions.TemplateDoesNotExist'>

base.html

Python version: 3.8.6
NetBox version: 3.0.2
```

**Comment by nikor30** [comment]
that would be great

**Comment by hiddenman** [comment]
@iDebugAll Hi.
Any plans to support 3.X version? Would be great.

Thank you.

**Comment by iDebugAll** [comment]
Hi all. NetBox 3.X compatibility is planned. There was even PR #9 from the community member @dathku – it required minor improvements to provide backward compatibility with older NetBox versions.
Hopefully, the update will be ready soon.

**Comment by iDebugAll** [comment]
Hi all. 
I have just published a new plugin release v0.0.2-beta.1 to provide general compatibility with NetBox 3.X.
It is backward compatible with older NetBox releases. Basic CRUD features worked fine in my tests. Some UI improvements are required.
As always, I will appreciate your feedback and suggestions.

**Comment by alexanderd24** [comment]
Hi all. I'm trying to install v0.0.2-beta.1 on NB 3.0.4 and getting following errors:
```
Running migrations:
  No migrations to apply.
  Your models in app(s): 'phonebox_plugin' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```
If I'm trying to open plugin from NB interface I see this message:

```
<class 'django.db.utils.ProgrammingError'>

relation "phonebox_plugin_number" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "phonebox_plugin_number"
                                          ^


Python version: 3.8.10
NetBox version: 3.0.4

```
What would be a solution for this?

**Comment by iDebugAll** [comment]
Hi @alexanderd24. Are you calling `makemigrations` using proper `venv`? Can you see the plugin installed in Django Admin?

**Comment by alexanderd24** [comment]
I'm calling `makemigrations` in the following way (without sudo):

source /opt/netbox/venv/bin/activate
cd /opt/netbox/netbox/
/opt/netbox/netbox$ python3 manage.py migrate

after that I'm getting error [described above](https://github.com/iDebugAll/phonebox_plugin/issues/8#issuecomment-933305242).
Running `makemigrations` after that leads to following output (with `migrate` warnings are the same):

```
/opt/netbox/netbox$ python3 manage.py makemigrations
/opt/netbox/netbox/netbox/settings.py:50: UserWarning: The CACHE_TIMEOUT configuration parameter was removed in v3.0.0 and no longer has any effect.
  warnings.warn(
/opt/netbox/netbox/netbox/settings.py:54: UserWarning: The RELEASE_CHECK_TIMEOUT configuration parameter was removed in v3.0.0 and no longer has any effect.
  warnings.warn(
CommandError: This command is available for development purposes only. It will
NOT resolve any issues with missing or unapplied migrations. For assistance,
please post to the NetBox discussion forum on GitHub:
    https://github.com/netbox-community/netbox/discussions
```

Installed plugin is listed in Django Admin:
![image](https://user-images.githubusercontent.com/91595340/135950171-e1c60601-24cb-4e4f-ac1e-bf2a7ca991e9.png)

**Comment by InsaneSplash** [comment]
Mine seems to be working again, thank you.

I ran a normal Netbox Update to 3.0.5 and received the error 

```
  No migrations to apply.
  Your models in app(s): 'phonebox_plugin' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

I then ran 
```
source /opt/netbox/venv/bin/activate
cd netbox/
./manage.py makemigrations
```

Recieved this error
```
CommandError: This command is available for development purposes only. It will
NOT resolve any issues with missing or unapplied migrations. For assistance,
please post to the NetBox discussion forum on GitHub:
    https://github.com/netbox-community/netbox/discussions

```
Then ran `upgrade.sh` again
The same error was shown, which I ignored, restarted netbox and it seemed to work fine.

**Comment by InsaneSplash** [comment]
![image](https://user-images.githubusercontent.com/16985649/136087846-b1d21e19-bd55-4559-bb7f-062d1684fb7a.png)

**Comment by michalceb** [comment]
I have been getting the migration error with the latest beta releases (since compatibility with v3 NB was introduced).

![image](https://user-images.githubusercontent.com/67379333/136236352-1667062c-0068-4606-a9a8-b97c96e220e1.png)

**Comment by alexanderd24** [comment]
> was phonebox_plugin listed in your NB local_requirements.txt as described in readme?

Yes. And when I'm running `upgrade.sh` I see this:

```
Installing local dependencies (pip install -r local_requirements.txt)...
Collecting phonebox_plugin
  Downloading phonebox_plugin-0.0.2b3.tar.gz (12 kB)
Building wheels for collected packages: phonebox-plugin
  Building wheel for phonebox-plugin (setup.py) ... done
  Created wheel for phonebox-plugin: filename=phonebox_plugin-0.0.2b3-py3-none-any.whl size=17272 sha256=5084cd1271bff76d2f00b75d2cd62408ea594270eb0245d9031a6f03c546758e
  Stored in directory: /root/.cache/pip/wheels/5d/58/98/88273ac80d18e2daf8082ca5d815f773cf7d7f37dbe5462123
Successfully built phonebox-plugin
Installing collected packages: phonebox-plugin
Successfully installed phonebox-plugin-0.0.2b3
Applying database migrations (python3 netbox/manage.py migrate)...
/opt/netbox/netbox/netbox/settings.py:50: UserWarning: The CACHE_TIMEOUT configuration parameter was removed in v3.0.0 and no longer has any effect.
  warnings.warn(
/opt/netbox/netbox/netbox/settings.py:54: UserWarning: The RELEASE_CHECK_TIMEOUT configuration parameter was removed in v3.0.0 and no longer has any effect.
  warnings.warn(
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, extras, ipam, sessions, taggit, tenancy, users, virtualization
Running migrations:
  No migrations to apply.

```
But plugin still not working in the frontend:
![image](https://user-images.githubusercontent.com/91595340/136339550-6a30f7fe-8c6a-4fd4-897c-b7aadb0f7462.png)

And when I'm trying to run `manage.py migrate` manually, I'm getting error:

```
source /opt/netbox/venv/bin/activate
cd /opt/netbox/netbox/
python3 manage.py migrate

/opt/netbox/netbox/netbox/settings.py:50: UserWarning: The CACHE_TIMEOUT configuration parameter was removed in v3.0.0 and no longer has any effect.
  warnings.warn(
/opt/netbox/netbox/netbox/settings.py:54: UserWarning: The RELEASE_CHECK_TIMEOUT configuration parameter was removed in v3.0.0 and no longer has any effect.
  warnings.warn(
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, extras, ipam, phonebox_plugin, sessions, taggit, tenancy, users, virtualization
Running migrations:
  No migrations to apply.
  Your models in app(s): 'phonebox_plugin' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```
Should the table `phonebox_plugin_number` be listed in Postgres? There is no such one in my tables list.

**Comment by Dees7** [comment]
Broken in last version 
```
<class 'django.urls.exceptions.NoReverseMatch'>
'phonebox_plugin' is not a registered namespace inside 'plugins'
Python version: 3.8.10
NetBox version: 3.1.1
```

```
python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox-3.1.1/netbox/netbox/urls.py", line 9, in <module>
    from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
  File "/opt/netbox-3.1.1/netbox/extras/plugins/urls.py", line 28, in <module>
    urlpatterns = import_object(f"{plugin_path}.urls.urlpatterns")
  File "/opt/netbox-3.1.1/netbox/extras/plugins/utils.py", line 31, in import_object
    spec.loader.exec_module(module)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/phonebox_plugin/urls.py", line 2, in <module>
    from . import views
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/phonebox_plugin/views.py", line 6, in <module>
    from . import forms
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/phonebox_plugin/forms.py", line 67, in <module>
    class NumberBulkEditForm(BootstrapMixin, AddRemoveTagsForm, BulkEditForm):
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/forms/forms.py", line 31, in __new__
    new_class = super().__new__(mcs, name, bases, attrs)
  File "/opt/netbox-3.1.1/venv/lib/python3.8/site-packages/django/forms/widgets.py", line 191, in __new__
    new_class = super().__new__(mcs, name, bases, attrs)
TypeError: Cannot create a consistent method resolution
order (MRO) for bases BootstrapMixin, AddRemoveTagsForm, BulkEditForm
```

**Comment by iDebugAll** [comment]
@Dees7 is `phonebox_plugin` listed in your NetBox's `local_requirements.txt`? Make sure the plugin was reinstalled during the upgrade procedure. Otherwise, follow the regular plugin installation guidelines.

**Comment by hiddenman** [comment]
@iDebugAll Hi,  
I've got exactly the same problem when upgrading 3.0.11 -> 3.1.1
So i've temporarily removed the plugin from the configuration.
Please, check the last error string.

**Comment by InsaneSplash** [comment]
Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/urls/resolvers.py", line 416, in check
    for pattern in self.url_patterns:
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/urls.py", line 9, in <module>
    from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
  File "/opt/netbox/netbox/extras/plugins/urls.py", line 28, in <module>
    urlpatterns = import_object(f"{plugin_path}.urls.urlpatterns")
  File "/opt/netbox/netbox/extras/plugins/utils.py", line 31, in import_object
    spec.loader.exec_module(module)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/phonebox_plugin/urls.py", line 2, in <module>
    from . import views
  File "/opt/netbox/venv/lib64/python3.8/site-packages/phonebox_plugin/views.py", line 6, in <module>
    from . import forms
  File "/opt/netbox/venv/lib64/python3.8/site-packages/phonebox_plugin/forms.py", line 67, in <module>
    class NumberBulkEditForm(BootstrapMixin, AddRemoveTagsForm, BulkEditForm):
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/forms/forms.py", line 31, in __new__
    new_class = super().__new__(mcs, name, bases, attrs)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/forms/widgets.py", line 191, in __new__
    new_class = super().__new__(mcs, name, bases, attrs)
**TypeError: Cannot create a consistent method resolution
order (MRO) for bases BootstrapMixin, AddRemoveTagsForm, BulkEditForm**

**Comment by InsaneSplash** [comment]
> Anyway, the fix is to find classes which has both BootstrapMixin and another class that inherits that and remove BootstrapMixin
> I guess BulkEditForm is one of those that also has BootstrapMixin
--Kim Johansson

**Comment by dnk2009** [comment]
The complete exception is provided below:

<class 'TypeError'>

Cannot create a consistent method resolution
order (MRO) for bases BootstrapMixin, AddRemoveTagsForm, BulkEditForm

Python version: 3.9.2
NetBox version: 3.1.2

**Comment by trakennedy** [comment]
Same issues here with Netbox 3.1.3. Issue appears to be the class NumberBulkEditform:

  File "/opt/netbox/venv/lib/python3.9/site-packages/phonebox_plugin/forms.py", line 67, in <module>
    class NumberBulkEditForm(BootstrapMixin, AddRemoveTagsForm, BulkEditForm):
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/forms/forms.py", line 31, in __new__
    new_class = super().__new__(mcs, name, bases, attrs)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/forms/widgets.py", line 191, in __new__
    new_class = super().__new__(mcs, name, bases, attrs)
TypeError: Cannot create a consistent method resolution
order (MRO) for bases BootstrapMixin, AddRemoveTagsForm, BulkEditForm

**Comment by InsaneSplash** [comment]
Probably going to have to move this back to a spreadsheet for the time being.

**Comment by bigbearct** [comment]
Is there a fix for this in the near future?

Looks like it would be very helpful for netbox newer editions.

I wish there were better step by step quides on installing the netbox plugins for new users to it....

**Comment by iDebugAll** [comment]
Hi all. Thank you for you feedback and patience. The latest plugin release v0.0.3-beta.7 contains compatibility fixes for NetBox 3.1.x versions.

**Comment by alexanderd24** [comment]
Hi. And now it works! Thank you @iDebugAll!

**Comment by bigbearct** [comment]
Almost got it to work , getting this error:;

i did the manage migrate in the instructions 

<class 'django.db.utils.ProgrammingError'>

relation "phonebox_plugin_voicecircuit" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "phonebox_plugin_voicecirc...

how to fix?

**Comment by trakennedy** [comment]
I get the same error. It looks like the PyPi version doesn't have the migrations/0003_voicecircuit.py file. I copied this file from the GitHub repo and then re-ran `python3 manage.py migrate` which applied that file. Afterwards everything seems fine.

**Comment by bigbearct** [comment]
> I get the same error. It looks like the PyPi version doesn't have the migrations/0003_voicecircuit.py file. I copied this file from the GitHub repo and then re-ran `python3 manage.py migrate` which applied that file. Afterwards everything seems fine.

Where is this missing?

How do I get it there?

Sorry very new to this program and adding plugins..

**Comment by iDebugAll** [comment]
@bigbearct @trakennedy PyPi package for v0.0.3-beta.7 was incomplete. 
New release v0.0.3-beta.8 should contain all necessary files. Thank you for a quick feedback.

**Comment by bigbearct** [comment]
> @bigbearct @trakennedy PyPi package for v0.0.3-beta.7 was incomplete. New release v0.0.3-beta.8 should contain all necessary files. Thank you for a quick feedback.

IT WORKS!!

Thank you , I think other users will find it very helpful ...

**Comment by trakennedy** [comment]
Confirmed, everything looks good. Great work, @iDebugAll!
